### ISSUE TITLE
Update a blog link to get info about the laptops/ devices/ gadgets discounts for students

### ISSUE THREAD

**Issue by baekusboo** [ShreyamMaity/student-offers#136]
I would like to suggest adding this link to get info about the laptops/ tablets/ gadgets discounts for students. There are a lot of companies which provide gadgets/electronic devices discounts for students. Unidays has a curated list here. So I would like to share this here but have no idea how to add it in the table format as specified. Hence, I am raising this issue.

https://www.myunidays.com/GB/en-GB/category/all-technology_laptops-and-tablets

Student discounts/ offers for technology gadgets from Lenovo, dell, apple, Samsung, HP, Acer etc are given. Kindly let me know if I can help contribute in any other way! Happy Hacktober! ^^

**Comment by ShreyamMaity** [comment]
That's an excellent idea. I'll encourage you to add it. Just go to the database folder and open the database.md file. Follow these MD syntax instructions to understand how MD tables work.
 https://github.com/ShreyamMaity/student-offers#instructions-to-contribute-
 If you face any issues, feel free to comment here.

**Comment by baekusboo** [comment]
Sure, I will add it. The link I shared is working on my end. Could you once check this link and let me know?

https://www.myunidays.com/IN/en-IN/content/about

**Comment by ShreyamMaity** [comment]
most probably you're logged in , that's why it's working. And the last link is working fine.
