### ISSUE TITLE
Update student offers database

### ISSUE THREAD

**Issue by anu-codes** [ShreyamMaity/student-offers#171]
Samsung and HP also offer student discounts on their products, and details for such should be added in the database.

**Comment by ShreyamMaity** [comment]
yes , you can add these.

**Comment by anu-codes** [comment]
Thank you for letting me contribute to this project! Please add hacktober fest label to my pr, it's still showing "not accepted" to me.

**Comment by ShreyamMaity** [comment]
Don't worry, your issue was marked as Hacktoberfest Accepted. And it takes up to 2 hours to show the updated status.

**Comment by anu-codes** [comment]
Alright, thanks for clearing my doubts :)
